### ISSUE TITLE
【BUG】沙盒调试，显示错误

### ISSUE THREAD

**Issue by lniuua** [XasYer/YePanel#51]
![image](https://github.com/user-attachments/assets/4b147190-86c5-474a-aa7e-b88cb829d035)

**Comment by XasYer** [comment]
哪里有错误

**Comment by lniuua** [comment]
机器人回复消息，显示的是管理员头像跟名字

**Comment by XasYer** [comment]
这里是沙盒调试,又不是和你已存在的Bot对话,所以是用登录用户的名字和头像

**Comment by lniuua** [comment]
懂了，谢谢了
